config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'

  get '/submit', to: 'orders#new'
  post '/submit', to: 'orders#create'

  resources :orders

  get '/knowledge', to: 'static_pages#knowledge'

end

app/models/order.rb
class Order < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def show
		@orders = Order.find(params[:id])
	end
# working renders the index with all orders showing
	def index
		@orders = Order.all
	end

# working renders the form
	def new
		@order = Order.new
	end

	
	def create
		@order = Order.new(order_params)
		if @order.save
			redirect_to root_path
			else
			redirect_to root_path			
		end
	end

	
	private
	
		def order_params
			params.require(:order).permit(:company, :address, :postcode, :provider, :alk, 
				:cssdistrict, :lorn, :appoint, :product, :numbercircref, :login, :password, 
				:ip, :ordereddate, :installdate, :prtg, :keepass, :billed, 
				:commandid1, :commandid2, :migration, :newprovide, :misc, :live, :speed)
		end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
	<%= link_to image_tag("pescado-hosted.jpg", size:"120x90", alt: "PescadoTank"), '#' , id: "logo" %>

	<nav>
	<ul class="nav navbar-nav navbar-right">
	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "Knowledge Base", '/knowledge' %></li>
	<li><%= link_to "New", '/orders/new' %></li>
	<li></li>

	</nav>
</div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PescadoTank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

 


</body>
</html>

app/views/orders/_form.html.erb
<div class="container">
	<div class="well">
		<div class="row">	
			<div class="col-md-6">
	
	<%= form_for(@order, url: submit_path) do |f| %>
	<%= render 'shared/error_messages' %>

	<%= f.label :company, "Customer/Company Name" %>
	<%= f.text_field :company, class: 'form-control' %>
	<p>
	
	<%= f.label :address, "Installation Address" %>
	<%= f.text_area :address, class: 'form-control' %>
	<p>

	<%= f.label :postcode, "Installation Postcode" %>
	<%= f.text_field :postcode, class: 'form-control' %>
	<p>

	<%= f.label :provider, "Provider Used" %>
	<%= f.text_field :provider, class: 'form-control' %>
	<p>
	
	<%= f.label :alk, "ALK" %>
	<%= f.text_field :alk, class: 'form-control' %>
	<p>

	<%= f.label :cssdistrict, "CSSDistrict Code" %>
	<%= f.text_field :cssdistrict, class: 'form-control' %>
	<p>
	</div>
	<div class="col-md-6">
	<%= f.label :lorn, "Linked Order Ref (LORN)" %>
	<%= f.text_field :lorn, class: 'form-control' %>
	<p>

	<%= f.label :appoint, "Appointment Code" %>
	<%= f.text_field :appoint, class: 'form-control' %>
	<p>

	<%= f.label :product, "Product Type" %>
	<%= f.text_field :product, class: 'form-control' %>
	<p>

	<%= f.label :numbercircref, "Number/Circuit Ref" %>
	<%= f.text_field :numbercircref, class: 'form-control' %>
	<p>

	<%= f.label :numbercircref, "Number/Circuit Ref (Optional)" %>
	<%= f.text_field :numbercircref, class: 'form-control' %>
	<p>

	<%= f.label :login, "Broadband Service Login" %>
	<%= f.text_field :login, class: 'form-control' %>
	<p>

	<%= f.label :password, "Broadband Service Password" %>
	<%= f.text_field :password, class: 'form-control' %>
	<p>

	</div>
	</div>
	</div>
<br>
	<div class="well">
	<div class="row">
	<div class="col-md-6">

	
	<%= f.label :ip, "IP Address" %>
	<%= f.text_field :ip, class: 'form-control' %>
	<p>

	<%= f.label :ordereddate, "Ordered Date" %>
	<%= f.text_field :ordereddate, class: 'form-control' %>
	<p>

	<%= f.label :installdate, "Install Date" %>
	<%= f.text_field :installdate, class: 'form-control' %>
	<p>

	<%= f.label :prtg, "PRTG Complete" %>
	<%= f.check_box :prtg, class: 'form-control' %>
	<p>

	<%= f.label :keepass, "Keepass Complete" %>
	<%= f.check_box :keepass, class: 'form-control' %>
	<p>

	<%= f.label :billed, "Billed?" %>
	<%= f.check_box :billed, class: 'form-control' %>
	
	<div class="col-md-6">

	<%= f.label :commandid1, "Command ID" %>
	<%= f.text_field :commandid1, class: 'form-control' %>
	<p>

	<%= f.label :commandid2, "Command ID2 (if applicable)" %>
	<%= f.text_field :commandid2, class: 'form-control' %>
	<p>

	<%= f.label :migration, "Migration" %>
	<%= f.check_box :migration, class: 'form-control' %>
	<p>

	<%= f.label :newprovide, "New Provide" %>
	<%= f.check_box :newprovide, class: 'form-control' %>
	<p>

	<%= f.label :misc, "Miscellaneous/Notes" %>
	<%= f.text_area :misc, class: 'form-control' %>
	<p>

	<%= f.label :speed, "Service Speed" %>
	<%= f.text_field :speed, class: 'form-control' %>
	<p>

	<%= f.label :live, "Live" %>
	<%= f.check_box :live, class: 'form-control' %>
	<p>
		</div>
	</div>
</div>

		<%= f.submit "Save Order", class: 'btn btn-warning' %>
	<% end %>	

</div>

app/views/orders/index.html.erb
<html>
<title>Ordering Platform</title>


<div class="container">
<div class="jumbotron">
	<h1> Pescado Tank - Order Centre  Click to view</h1>
<%= link_to "New Order", '/orders/new', class: "btn btn-warning" %>

<br>
<p>

<div class="well" class="col-md-4">
	
<% @orders.each do |order| %><li>
<%=	link_to order.company, order %></li>
<% end %>

</div>
</div>
</div>

</html>

app/views/orders/knowledge.html.erb
Knowledge Base Articles

app/views/orders/new.html.erb
<html>

<title>New Order</title>
<h1>New Order</h1>

<div class="container-fluid">

<%= render 'form' %>

</div>

</html>

app/views/orders/show.html.erb
<div class="well">
	<%= @order %>
</div>

app/views/shared/_error_messages.html.erb
<% if @order.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@order.errors.count, "error") %>.
    </div>
    <ul>
    <% @order.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/knowledge.html.erb
Knowledge Base Articles